export type ProjectItem = {
  id: string;
  letter: string;
  name: string;
  city: string;
  type: string;
  status: "Livré" | "En cours" | "Étude";
  summary: string;
  durationMonths: number;
  
  // Fiche technique avancée
  client?: string;
  mission?: string;
  sector?: string;
  surface?: string;
  year?: string;
  team?: string;
  services?: string;
  tech?: string;
  referent?: string;

  media?: string[];
};

export const constructionProjects: ProjectItem[] = [
  {
    id: "avagout-abidjan",
    letter: "A",
    name: "Projet AVAGOUT Jacques",
    city: "Abidjan",
    type: "Résidentiel",
    status: "Livré",
    summary: "Ouvrage résidentiel avec suivi technique, second œuvre et finitions.",
    durationMonths: 18,
    client: "Client Privé",
    mission: "Maîtrise d'œuvre complète",
    sector: "Immobilier Résidentiel Haut de Gamme",
    surface: "850 m²",
    year: "2023",
    team: "1 Chef de projet, 2 Ingénieurs, 15 Ouvriers qualifiés",
    services: "Gros œuvre, Électricité, Plomberie, Aménagements intérieurs",
    tech: "Béton armé optimisé, Modélisation BIM 3D",
    referent: "Ing. Koffi",
    media: [
      "/media/projects/avagout-abidjan/WhatsApp Image 2026-05-11 at 19.17.04 (1).jpeg",
      "/media/projects/avagout-abidjan/WhatsApp Image 2026-05-11 at 19.17.04 (2).jpeg",
      "/media/projects/avagout-abidjan/WhatsApp Image 2026-05-11 at 19.17.04 (3).jpeg",
      "/media/projects/avagout-abidjan/WhatsApp Image 2026-05-11 at 19.17.04 (4).jpeg",
      "/media/projects/avagout-abidjan/WhatsApp Image 2026-05-11 at 19.17.04 (5).jpeg",
      "/media/projects/avagout-abidjan/WhatsApp Image 2026-05-11 at 19.17.04 (6).jpeg",
      "/media/projects/avagout-abidjan/WhatsApp Image 2026-05-11 at 19.17.04 (7).jpeg",
      "/media/projects/avagout-abidjan/WhatsApp Image 2026-05-11 at 19.17.04.jpeg"
    ],
  },
  {
    id: "bingerville-r3",
    letter: "B",
    name: "Étude de sol R+3 Bingerville",
    city: "Bingerville",
    type: "Ingénierie",
    status: "Étude",
    summary: "Reconnaissance de sol et préconisations structurelles pour un projet R+3.",
    durationMonths: 6,
    client: "SCI Horizon",
    mission: "Étude Géotechnique et Structurelle",
    sector: "Immobilier Commercial",
    surface: "1 200 m²",
    year: "2024",
    team: "1 Ingénieur Géotechnicien, 1 Projeteur",
    services: "Sondages pénétrométriques, Essais en laboratoire, Note de calcul",
    tech: "Logiciels de dimensionnement sismique, Essais in-situ",
    referent: "Ing. Bamba",
    media: [
      "/media/projects/bingerville-r3/WhatsApp Image 2026-05-11 at 19.32.08 (1).jpeg",
      "/media/projects/bingerville-r3/WhatsApp Image 2026-05-11 at 19.32.08 (2).jpeg",
      "/media/projects/bingerville-r3/WhatsApp Image 2026-05-11 at 19.32.08.jpeg",
      "/media/projects/bingerville-r3/WhatsApp Image 2026-05-11 at 19.32.09 (1).jpeg",
      "/media/projects/bingerville-r3/WhatsApp Image 2026-05-11 at 19.32.09 (2).jpeg",
      "/media/projects/bingerville-r3/WhatsApp Image 2026-05-11 at 19.32.09 (3).jpeg",
      "/media/projects/bingerville-r3/WhatsApp Image 2026-05-11 at 19.32.09.jpeg"
    ],
  },
  {
    id: "cocody-extension",
    letter: "C",
    name: "Projet Cocody Extension",
    city: "Abidjan",
    type: "Extension / Réhabilitation",
    status: "Livré",
    summary: "Extension d'ouvrage existant avec renforcement et optimisation des volumes.",
    durationMonths: 12,
    client: "Ministère / Institution",
    mission: "Conception et Réalisation",
    sector: "Bâtiment Public / Institutionnel",
    surface: "450 m²",
    year: "2022",
    team: "1 Conducteur de travaux, 10 Compagnons",
    services: "Renforcement de fondations, Reprises en sous-œuvre, Extension",
    tech: "Micro-pieux, Coulage béton spécial",
    referent: "Ing. Touré",
    media: [
      "/media/projects/cocody-extension/WhatsApp Image 2026-05-11 at 19.20.56 (1).jpeg",
      "/media/projects/cocody-extension/WhatsApp Image 2026-05-11 at 19.20.56.jpeg",
      "/media/projects/cocody-extension/WhatsApp Image 2026-05-11 at 19.20.57 (1).jpeg",
      "/media/projects/cocody-extension/WhatsApp Image 2026-05-11 at 19.20.57 (2).jpeg",
      "/media/projects/cocody-extension/WhatsApp Image 2026-05-11 at 19.20.57 (3).jpeg",
      "/media/projects/cocody-extension/WhatsApp Image 2026-05-11 at 19.20.57 (4).jpeg",
      "/media/projects/cocody-extension/WhatsApp Image 2026-05-11 at 19.20.57 (5).jpeg",
      "/media/projects/cocody-extension/WhatsApp Image 2026-05-11 at 19.20.57 (6).jpeg",
      "/media/projects/cocody-extension/WhatsApp Image 2026-05-11 at 19.20.57 (7).jpeg",
      "/media/projects/cocody-extension/WhatsApp Image 2026-05-11 at 19.20.57.jpeg",
      "/media/projects/cocody-extension/WhatsApp Image 2026-05-11 at 19.20.58.jpeg"
    ],
  },
  {
    id: "dabre-villa",
    letter: "D",
    name: "Projet DABRÉ - Villa basse",
    city: "Abidjan",
    type: "Villa",
    status: "Livré",
    summary: "Étude de sol, terrassement, fondations, gros œuvre et finition complète.",
    durationMonths: 24,
    client: "Famille DABRÉ",
    mission: "Projet Clé en main",
    sector: "Résidentiel",
    surface: "320 m²",
    year: "2024",
    team: "1 Chef de chantier, 12 Ouvriers polyvalents",
    services: "Gros œuvre, Étanchéité, Domotique, Paysagisme",
    tech: "Isolation thermique, Béton hydrofuge",
    referent: "Ing. Koffi",
    media: [
      "/media/projects/dabre-villa/WhatsApp Image 2026-05-12 at 06.54.36 (1).jpeg",
      "/media/projects/dabre-villa/WhatsApp Image 2026-05-12 at 06.54.36 (2).jpeg",
      "/media/projects/dabre-villa/WhatsApp Image 2026-05-12 at 06.54.36 (3).jpeg",
      "/media/projects/dabre-villa/WhatsApp Image 2026-05-12 at 06.54.36.jpeg",
      "/media/projects/dabre-villa/WhatsApp Image 2026-05-12 at 06.54.37 (1).jpeg",
      "/media/projects/dabre-villa/WhatsApp Image 2026-05-12 at 06.54.37 (2).jpeg",
      "/media/projects/dabre-villa/WhatsApp Image 2026-05-12 at 06.54.37 (3).jpeg",
      "/media/projects/dabre-villa/WhatsApp Image 2026-05-12 at 06.54.37.jpeg"
    ],
  },
  {
    id: "gbakayo-soubre",
    letter: "G",
    name: "Projet GBAKAYO",
    city: "Soubré",
    type: "Résidentiel",
    status: "Livré",
    summary: "Construction résidentielle avec pilotage de chantier et contrôle qualité.",
    durationMonths: 18,
    client: "Investisseur Local",
    mission: "Pilotage et Maîtrise d'ouvrage déléguée",
    sector: "Immobilier Résidentiel",
    surface: "1 800 m²",
    year: "2023",
    team: "1 Ingénieur Travaux, 20 Ouvriers",
    services: "Pilotage TCE (Tous Corps d'État), Suivi financier",
    tech: "Gestion de chantier digitalisée (SICA ERP)",
    referent: "Ing. Bamba",
    media: [
      "/media/projects/gbakayo-soubre/WhatsApp Image 2026-05-11 at 19.39.29 (1).jpeg",
      "/media/projects/gbakayo-soubre/WhatsApp Image 2026-05-11 at 19.39.29 (2).jpeg",
      "/media/projects/gbakayo-soubre/WhatsApp Image 2026-05-11 at 19.39.29 (3).jpeg",
      "/media/projects/gbakayo-soubre/WhatsApp Image 2026-05-11 at 19.39.29.jpeg",
      "/media/projects/gbakayo-soubre/WhatsApp Image 2026-05-11 at 19.39.30.jpeg"
    ],
  },
  {
    id: "guessiguie-agboville",
    letter: "G",
    name: "Projet GUESSIGUIÉ",
    city: "Agboville",
    type: "Résidentiel",
    status: "Livré",
    summary: "Déploiement chantier avec planning de lots et coordination multi-corps d'état.",
    durationMonths: 20,
    client: "Promoteur Privé",
    mission: "Maîtrise d'œuvre d'Exécution",
    sector: "Promotion Immobilière",
    surface: "15 000 m²",
    year: "2025",
    team: "1 Directeur de Projet, 3 Conducteurs de travaux, 50+ Compagnons",
    services: "Coordination de sous-traitants, Contrôle Qualité",
    tech: "BIM 4D (Planification avancée)",
    referent: "Ing. Touré",
    media: [
      "/media/projects/guessiguie-agboville/WhatsApp Image 2026-05-12 at 06.49.18 (1).jpeg",
      "/media/projects/guessiguie-agboville/WhatsApp Image 2026-05-12 at 06.49.18 (2).jpeg",
      "/media/projects/guessiguie-agboville/WhatsApp Image 2026-05-12 at 06.49.18 (3).jpeg",
      "/media/projects/guessiguie-agboville/WhatsApp Image 2026-05-12 at 06.49.18 (4).jpeg",
      "/media/projects/guessiguie-agboville/WhatsApp Image 2026-05-12 at 06.49.18 (5).jpeg",
      "/media/projects/guessiguie-agboville/WhatsApp Image 2026-05-12 at 06.49.18.jpeg"
    ],
  },
  {
    id: "jacqueville-villa-duplex",
    letter: "J",
    name: "Villa Duplex Jacqueville",
    city: "Jacqueville",
    type: "Villa Duplex",
    status: "Livré",
    summary: "Construction de villa duplex, gros œuvre, réseaux techniques et aménagement.",
    durationMonths: 15,
    client: "Client Privé",
    mission: "Construction Clé en main",
    sector: "Résidentiel Balnéaire",
    surface: "600 m²",
    year: "2024",
    team: "1 Chef de chantier, 15 Ouvriers spécialisés",
    services: "Construction complète, Finitions Premium, Piscine",
    tech: "Traitements anti-corrosion (milieu marin)",
    referent: "Ing. Koffi",
    media: [
      "/media/projects/jacqueville-villa-duplex/WhatsApp Image 2026-05-11 at 19.29.47 (1).jpeg",
      "/media/projects/jacqueville-villa-duplex/WhatsApp Image 2026-05-11 at 19.29.47 (2).jpeg",
      "/media/projects/jacqueville-villa-duplex/WhatsApp Image 2026-05-11 at 19.29.47 (3).jpeg",
      "/media/projects/jacqueville-villa-duplex/WhatsApp Image 2026-05-11 at 19.29.47.jpeg",
      "/media/projects/jacqueville-villa-duplex/WhatsApp Image 2026-05-11 at 19.29.48.jpeg"
    ],
  },
  {
    id: "ocalm-km53",
    letter: "O",
    name: "Projet O'CALM km53",
    city: "Abidjan",
    type: "Infrastructure",
    status: "En cours",
    summary: "Intervention chantier km53 avec suivi des lots, métrés et contrôles périodiques.",
    durationMonths: 36,
    client: "O'CALM SA",
    mission: "Génie Civil & OPC",
    sector: "Industriel / Logistique",
    surface: "12 000 m²",
    year: "2025",
    team: "2 Ingénieurs Civils, 1 Géomètre, 40+ Ouvriers",
    services: "Terrassement lourd, VRD, Fondations profondes",
    tech: "Levés topographiques par drone",
    referent: "Ing. Bamba",
    media: [
      "/media/projects/ocalm-km53/WhatsApp Image 2026-05-11 at 19.19.28 (1).jpeg",
      "/media/projects/ocalm-km53/WhatsApp Image 2026-05-11 at 19.19.28 (2).jpeg",
      "/media/projects/ocalm-km53/WhatsApp Image 2026-05-11 at 19.19.28.jpeg",
      "/media/projects/ocalm-km53/WhatsApp Image 2026-05-11 at 19.19.29 (1).jpeg",
      "/media/projects/ocalm-km53/WhatsApp Image 2026-05-11 at 19.19.29 (2).jpeg",
      "/media/projects/ocalm-km53/WhatsApp Image 2026-05-11 at 19.19.29 (3).jpeg",
      "/media/projects/ocalm-km53/WhatsApp Image 2026-05-11 at 19.19.29 (4).jpeg",
      "/media/projects/ocalm-km53/WhatsApp Image 2026-05-11 at 19.19.29.jpeg"
    ],
  },
  {
    id: "sgci-plateau",
    letter: "S",
    name: "Siège SGCI Plateau",
    city: "Abidjan",
    type: "Corporate / Géobéton",
    status: "Livré",
    summary: "Projet signature en géobéton, maîtrise des délais et des performances structurelles.",
    durationMonths: 48,
    client: "Société Générale CI",
    mission: "Maîtrise d'œuvre spécialisée",
    sector: "Bâtiment Tertiaire (Corporate)",
    surface: "2 500 m²",
    year: "2023",
    team: "1 Chef de projet senior, Ingénieurs Matériaux, 60+ Compagnons",
    services: "Structure Innovante, Suivi Architectural",
    tech: "Géobéton (Béton de terre stabilisée), Normes HQE",
    referent: "Ing. Touré",
    media: [
      "/media/projects/sgci-plateau/WhatsApp Image 2026-05-11 at 19.15.32 (1).jpeg",
      "/media/projects/sgci-plateau/WhatsApp Image 2026-05-11 at 19.15.32.jpeg",
      "/media/projects/sgci-plateau/WhatsApp Image 2026-05-11 at 19.15.33 (1).jpeg",
      "/media/projects/sgci-plateau/WhatsApp Image 2026-05-11 at 19.15.33 (2).jpeg",
      "/media/projects/sgci-plateau/WhatsApp Image 2026-05-11 at 19.15.33 (3).jpeg",
      "/media/projects/sgci-plateau/WhatsApp Image 2026-05-11 at 19.15.33 (4).jpeg",
      "/media/projects/sgci-plateau/WhatsApp Image 2026-05-11 at 19.15.33 (5).jpeg",
      "/media/projects/sgci-plateau/WhatsApp Image 2026-05-11 at 19.15.33 (6).jpeg",
      "/media/projects/sgci-plateau/WhatsApp Image 2026-05-11 at 19.15.33 (7).jpeg",
      "/media/projects/sgci-plateau/WhatsApp Image 2026-05-11 at 19.15.33.jpeg"
    ],
  },
  {
    id: "songon-abidjan",
    letter: "S",
    name: "Projet SONGON",
    city: "Abidjan",
    type: "Résidentiel",
    status: "Livré",
    summary: "Conception-réalisation d'ouvrage résidentiel avec contrôle qualité renforcé.",
    durationMonths: 14,
    client: "Mairie / Institutionnel",
    mission: "Entreprise Générale",
    sector: "Logement Public",
    surface: "8 000 m²",
    year: "2022",
    team: "2 Conducteurs de travaux, 35 Ouvriers",
    services: "Construction standardisée, Aménagements collectifs",
    tech: "Préfabrication d'éléments béton",
    referent: "Ing. Koffi",
    media: [
      "/media/projects/songon-abidjan/WhatsApp Image 2026-05-11 at 19.34.03 (1).jpeg",
      "/media/projects/songon-abidjan/WhatsApp Image 2026-05-11 at 19.34.03.jpeg",
      "/media/projects/songon-abidjan/WhatsApp Image 2026-05-11 at 19.34.04 (1).jpeg",
      "/media/projects/songon-abidjan/WhatsApp Image 2026-05-11 at 19.34.04 (2).jpeg",
      "/media/projects/songon-abidjan/WhatsApp Image 2026-05-11 at 19.34.04.jpeg"
    ],
  },
  {
    id: "y4-cocody",
    letter: "Y",
    name: "Projet Y4 Cocody",
    city: "Abidjan",
    type: "Résidentiel",
    status: "Livré",
    summary: "Projet urbain en zone dense, séquencement chantier et sécurité de site.",
    durationMonths: 22,
    client: "AGEROUTE (Sous-traitance)",
    mission: "Assistance et Exécution",
    sector: "Infrastructure Urbaine",
    surface: "N/A (Linéaire)",
    year: "2024",
    team: "1 Ingénieur Routier, Topographes, 25 Compagnons",
    services: "Soutènements, Ouvrages d'art annexes",
    tech: "Béton projeté, Stabilisation de talus",
    referent: "Ing. Bamba",
    media: [
      "/media/projects/y4-cocody/WhatsApp Image 2026-05-11 at 19.40.51 (1).jpeg",
      "/media/projects/y4-cocody/WhatsApp Image 2026-05-11 at 19.40.51 (2).jpeg",
      "/media/projects/y4-cocody/WhatsApp Image 2026-05-11 at 19.40.51 (3).jpeg",
      "/media/projects/y4-cocody/WhatsApp Image 2026-05-11 at 19.40.51.jpeg",
      "/media/projects/y4-cocody/WhatsApp Image 2026-05-11 at 19.40.52 (1).jpeg",
      "/media/projects/y4-cocody/WhatsApp Image 2026-05-11 at 19.40.52 (2).jpeg",
      "/media/projects/y4-cocody/WhatsApp Image 2026-05-11 at 19.40.52.jpeg"
    ],
  },
];

export const projectLetters = Array.from(
  new Set(constructionProjects.map((project) => project.letter)),
).sort();
