import {
  AlertCircle,
  Bell,
  Building2,
  CalendarDays,
  Camera,
  CheckCircle2,
  ClipboardList,
  Database,
  FileSignature,
  FileText,
  FolderKanban,
  HardHat,
  Inbox,
  KeyRound,
  MapPin,
  MessageSquareText,
  ReceiptText,
  Settings,
  ShieldCheck,
  Sparkles,
  TrendingUp,
  Users,
  Wallet,
} from "lucide-react";

export const ADMIN_MODULES = [
  { group: "Direction", label: "Vue dirigeant", desc: "Synthèse globale de l'entreprise.", status: "Actif", icon: TrendingUp },
  { group: "Direction", label: "KPI temps reel", desc: "Clients, projets, documents, demandes.", status: "Actif", icon: TrendingUp },
  { group: "Direction", label: "Pipeline operations", desc: "Suivi des dossiers ouverts.", status: "Actif", icon: FolderKanban },
  { group: "Direction", label: "Risques & alertes", desc: "Retards, blocages, signatures.", status: "À connecter", icon: AlertCircle },
  { group: "Direction", label: "Journal activité", desc: "Evenements internes et client.", status: "À connecter", icon: ClipboardList },
  { group: "Direction", label: "Plan d'action", desc: "Priorités de la semaine.", status: "Prévu", icon: CheckCircle2 },
  { group: "Direction", label: "Comité direction", desc: "Lecture executive mensuelle.", status: "Prévu", icon: Users },
  { group: "Direction", label: "Objectifs annuels", desc: "Cap, croissance et performance.", status: "Prévu", icon: TrendingUp },

  { group: "Clients", label: "Fichier clients", desc: "Comptes et contacts clients.", status: "Actif", icon: Users },
  { group: "Clients", label: "Création client", desc: "Compte, mot de passe, seed espace.", status: "Actif", icon: Users },
  { group: "Clients", label: "Fiche 360 client", desc: "Contrats, projets, demandes, documents.", status: "À connecter", icon: FileText },
  { group: "Clients", label: "Historique client", desc: "Trajectoire complète du compte.", status: "À connecter", icon: ClipboardList },
  { group: "Clients", label: "Segments clients", desc: "Particulier, PME, institutionnel.", status: "Prévu", icon: Users },
  { group: "Clients", label: "Relances client", desc: "Signature, paiement, documents manquants.", status: "Prévu", icon: Bell },
  { group: "Clients", label: "Satisfaction", desc: "Retour experience et suivi qualite.", status: "Prévu", icon: CheckCircle2 },
  { group: "Clients", label: "Portefeuille commercial", desc: "Prospects et clients actifs.", status: "Prévu", icon: FolderKanban },

  { group: "Chantiers", label: "Chantiers actifs", desc: "Opérations BTP en cours.", status: "Actif", icon: HardHat },
  { group: "Chantiers", label: "Avancement physique", desc: "Progression et jalons chantier.", status: "Actif", icon: TrendingUp },
  { group: "Chantiers", label: "Carte projets", desc: "Localisations et zones d'intervention.", status: "À connecter", icon: MapPin },
  { group: "Chantiers", label: "Photos terrain", desc: "Preuves visuelles geolocalisees.", status: "À connecter", icon: Camera },
  { group: "Chantiers", label: "Rapports terrain", desc: "Comptes rendus et observations.", status: "À connecter", icon: FileText },
  { group: "Chantiers", label: "Planning chantier", desc: "Jalons, equipes, delais.", status: "Prévu", icon: CalendarDays },
  { group: "Chantiers", label: "Équipes affectees", desc: "Responsables et intervenants.", status: "Prévu", icon: Users },
  { group: "Chantiers", label: "Matériels", desc: "Engins, outils et disponibilité.", status: "Prévu", icon: Settings },
  { group: "Chantiers", label: "Sous-traitants", desc: "Partenaires terrain et lots.", status: "Prévu", icon: Building2 },
  { group: "Chantiers", label: "Réception travaux", desc: "Reserves, livraison, validation.", status: "Prévu", icon: CheckCircle2 },

  { group: "Documents", label: "Devis IA", desc: "Console d'apprentissage du moteur de devis IA.", status: "Actif", icon: Sparkles },
  { group: "Documents", label: "GED documents", desc: "Devis, contrats, factures.", status: "Actif", icon: FileText },
  { group: "Documents", label: "Documents a signer", desc: "Suivi des signatures client.", status: "Actif", icon: FileSignature },
  { group: "Documents", label: "Contrats", desc: "Pièces contractuelles centralisées.", status: "À connecter", icon: FileSignature },
  { group: "Documents", label: "Devis Construction", desc: "Connexion au simulateur existant.", status: "À connecter", icon: ReceiptText },
  { group: "Documents", label: "Factures", desc: "Émission et suivi facture.", status: "Prévu", icon: Wallet },
  { group: "Documents", label: "Paiements", desc: "Règlements, échéances, soldes.", status: "Prévu", icon: Wallet },
  { group: "Documents", label: "Versioning", desc: "Historique de versions documentaires.", status: "Prévu", icon: Database },
  { group: "Documents", label: "Archive sécurisée", desc: "Conservation et traçabilité.", status: "Prévu", icon: ShieldCheck },
  { group: "Documents", label: "Bon de commande", desc: "Validation achats et prestations.", status: "Prévu", icon: ReceiptText },
  { group: "Documents", label: "Export reporting", desc: "Sorties PDF, Word, direction.", status: "Prévu", icon: FileText },

  { group: "Assistance", label: "Demandes clients", desc: "Tickets et fiches qualifiées.", status: "Actif", icon: Inbox },
  { group: "Assistance", label: "Dossiers juridiques", desc: "Actes, statuts, formalités.", status: "À connecter", icon: FileSignature },
  { group: "Assistance", label: "Comptabilité", desc: "Suivi comptable et obligations.", status: "À connecter", icon: ReceiptText },
  { group: "Assistance", label: "Fiscalité", desc: "Declarations et calendrier fiscal.", status: "Prévu", icon: CalendarDays },
  { group: "Assistance", label: "Création entreprise", desc: "RCCM et constitution légale.", status: "Prévu", icon: Building2 },
  { group: "Assistance", label: "RH client", desc: "Dossiers sociaux et personnel.", status: "Prévu", icon: Users },
  { group: "Assistance", label: "Suivi administratif", desc: "Pièces attendues et étapes.", status: "Prévu", icon: ClipboardList },

  { group: "Systeme", label: "Rôles & permissions", desc: "Admin, staff, client.", status: "Actif", icon: KeyRound },
  { group: "Systeme", label: "Notifications", desc: "Alertes admin et client.", status: "À connecter", icon: Bell },
  { group: "Systeme", label: "Messagerie", desc: "Échanges admin-client.", status: "Prévu", icon: MessageSquareText },
  { group: "Systeme", label: "Sessions actives", desc: "Sécurité des connexions.", status: "Prévu", icon: ShieldCheck },
  { group: "Systeme", label: "Audit log", desc: "Journal des actions sensibles.", status: "Prévu", icon: ClipboardList },
  { group: "Systeme", label: "Base de données", desc: "Tables, synchronisation, sante.", status: "À connecter", icon: Database },
  { group: "Systeme", label: "Paramètres plateforme", desc: "Preferences, langues, règles.", status: "Prévu", icon: Settings },
] as const;

export type AdminModuleStatus = (typeof ADMIN_MODULES)[number]["status"];
